// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: consumptions.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteConsumptionsBefore = `-- name: DeleteConsumptionsBefore :exec
DELETE FROM consumptions
WHERE user_id = $1 AND ts < $2
`

type DeleteConsumptionsBeforeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Ts     time.Time `json:"ts"`
}

func (q *Queries) DeleteConsumptionsBefore(ctx context.Context, arg DeleteConsumptionsBeforeParams) error {
	_, err := q.db.Exec(ctx, deleteConsumptionsBefore, arg.UserID, arg.Ts)
	return err
}

const insertConsumption = `-- name: InsertConsumption :exec
INSERT INTO consumptions (user_id, ts, tea_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, ts, tea_id) DO NOTHING
`

type InsertConsumptionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Ts     time.Time `json:"ts"`
	TeaID  uuid.UUID `json:"tea_id"`
}

func (q *Queries) InsertConsumption(ctx context.Context, arg InsertConsumptionParams) error {
	_, err := q.db.Exec(ctx, insertConsumption, arg.UserID, arg.Ts, arg.TeaID)
	return err
}

const listConsumptionsSince = `-- name: ListConsumptionsSince :many
SELECT ts, tea_id
FROM consumptions
WHERE user_id = $1 AND ts >= $2
ORDER BY ts DESC
`

type ListConsumptionsSinceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Ts     time.Time `json:"ts"`
}

type ListConsumptionsSinceRow struct {
	Ts    time.Time `json:"ts"`
	TeaID uuid.UUID `json:"tea_id"`
}

func (q *Queries) ListConsumptionsSince(ctx context.Context, arg ListConsumptionsSinceParams) ([]ListConsumptionsSinceRow, error) {
	rows, err := q.db.Query(ctx, listConsumptionsSince, arg.UserID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsumptionsSinceRow{}
	for rows.Next() {
		var i ListConsumptionsSinceRow
		if err := rows.Scan(&i.Ts, &i.TeaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
