// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: devices.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, user_id, token)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertDeviceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.Exec(ctx, insertDevice, arg.ID, arg.UserID, arg.Token)
	return err
}

const listDeviceTokens = `-- name: ListDeviceTokens :many
SELECT token
FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeviceTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceToken = `-- name: UpdateDeviceToken :exec
UPDATE devices
SET token = $2
WHERE id = $1
`

type UpdateDeviceTokenParams struct {
	ID    uuid.UUID `json:"id"`
	Token string    `json:"token"`
}

func (q *Queries) UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceToken, arg.ID, arg.Token)
	return err
}
