// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type CollectionQrItem struct {
	CollectionID uuid.UUID `json:"collection_id"`
	QrID         uuid.UUID `json:"qr_id"`
}

type Consumption struct {
	UserID uuid.UUID `json:"user_id"`
	Ts     time.Time `json:"ts"`
	TeaID  uuid.UUID `json:"tea_id"`
}

type Device struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      int16     `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type QrRecord struct {
	ID             uuid.UUID `json:"id"`
	TeaID          uuid.UUID `json:"tea_id"`
	BoilingTemp    int32     `json:"boiling_temp"`
	ExpirationDate time.Time `json:"expiration_date"`
	CreatedAt      time.Time `json:"created_at"`
}

type Tag struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Color      string    `json:"color"`
	CategoryID uuid.UUID `json:"category_id"`
}

type TagCategory struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Tea struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TeaTag struct {
	TeaID uuid.UUID `json:"tea_id"`
	TagID uuid.UUID `json:"tag_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	AppleID   string    `json:"apple_id"`
	CreatedAt time.Time `json:"created_at"`
}
