// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tags.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const addTagToTea = `-- name: AddTagToTea :exec
INSERT INTO tea_tags (tea_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (tea_id, tag_id) DO NOTHING
`

type AddTagToTeaParams struct {
	TeaID uuid.UUID `json:"tea_id"`
	TagID uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToTea(ctx context.Context, arg AddTagToTeaParams) error {
	_, err := q.db.Exec(ctx, addTagToTea, arg.TeaID, arg.TagID)
	return err
}

const changeTagCategory = `-- name: ChangeTagCategory :one
UPDATE tags
SET category_id = $2
WHERE id = $1
RETURNING id, name, color, category_id
`

type ChangeTagCategoryParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) ChangeTagCategory(ctx context.Context, arg ChangeTagCategoryParams) (Tag, error) {
	row := q.db.QueryRow(ctx, changeTagCategory, arg.ID, arg.CategoryID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CategoryID,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const deleteTagCategory = `-- name: DeleteTagCategory :exec
DELETE FROM tag_categories WHERE id = $1
`

func (q *Queries) DeleteTagCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagCategory, id)
	return err
}

const deleteTagFromTea = `-- name: DeleteTagFromTea :exec
DELETE FROM tea_tags WHERE tea_id = $1 AND tag_id = $2
`

type DeleteTagFromTeaParams struct {
	TeaID uuid.UUID `json:"tea_id"`
	TagID uuid.UUID `json:"tag_id"`
}

func (q *Queries) DeleteTagFromTea(ctx context.Context, arg DeleteTagFromTeaParams) error {
	_, err := q.db.Exec(ctx, deleteTagFromTea, arg.TeaID, arg.TagID)
	return err
}

const deleteTagsByCategory = `-- name: DeleteTagsByCategory :exec
DELETE FROM tags
WHERE category_id = $1
`

func (q *Queries) DeleteTagsByCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagsByCategory, categoryID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, category_id
FROM tags
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CategoryID,
	)
	return i, err
}

const getTagCategory = `-- name: GetTagCategory :one
SELECT id, name
FROM tag_categories
WHERE id = $1
`

func (q *Queries) GetTagCategory(ctx context.Context, id uuid.UUID) (TagCategory, error) {
	row := q.db.QueryRow(ctx, getTagCategory, id)
	var i TagCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (id, name, color, category_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, category_id
`

type InsertTagParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Color      string    `json:"color"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.CategoryID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CategoryID,
	)
	return i, err
}

const insertTagCategory = `-- name: InsertTagCategory :one
INSERT INTO tag_categories (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type InsertTagCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) InsertTagCategory(ctx context.Context, arg InsertTagCategoryParams) (TagCategory, error) {
	row := q.db.QueryRow(ctx, insertTagCategory, arg.ID, arg.Name)
	var i TagCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTagCategories = `-- name: ListTagCategories :many
SELECT id, name
FROM tag_categories
ORDER BY name ASC
`

func (q *Queries) ListTagCategories(ctx context.Context) ([]TagCategory, error) {
	rows, err := q.db.Query(ctx, listTagCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagCategory{}
	for rows.Next() {
		var i TagCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, category_id
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByCategory = `-- name: ListTagsByCategory :many
SELECT id, name, color, category_id
FROM tags
WHERE category_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTagsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByCategoryFilter = `-- name: ListTagsByCategoryFilter :many
SELECT id, name, color, category_id
FROM tags
WHERE category_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTagsByCategoryFilter(ctx context.Context, categoryID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByCategoryFilter, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByName = `-- name: ListTagsByName :many
SELECT id, name, color, category_id
FROM tags
WHERE lower(name) LIKE lower($1) || '%'
ORDER BY name ASC
`

func (q *Queries) ListTagsByName(ctx context.Context, lower string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByName, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByNameCategory = `-- name: ListTagsByNameCategory :many
SELECT id, name, color, category_id
FROM tags
WHERE lower(name) LIKE lower($1) || '%'
  AND category_id = $2
ORDER BY name ASC
`

type ListTagsByNameCategoryParams struct {
	Lower      string    `json:"lower"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) ListTagsByNameCategory(ctx context.Context, arg ListTagsByNameCategoryParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByNameCategory, arg.Lower, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByTea = `-- name: ListTagsByTea :many
SELECT t.id, t.name, t.color, t.category_id
FROM tea_tags tt
JOIN tags t ON t.id = tt.tag_id
WHERE tt.tea_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByTea(ctx context.Context, teaID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByTea, teaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTagCategories = `-- name: SearchTagCategories :many
SELECT id, name
FROM tag_categories
WHERE lower(name) LIKE lower($1) || '%'
ORDER BY name ASC
`

func (q *Queries) SearchTagCategories(ctx context.Context, lower string) ([]TagCategory, error) {
	rows, err := q.db.Query(ctx, searchTagCategories, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagCategory{}
	for rows.Next() {
		var i TagCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2,
    color = $3
WHERE id = $1
RETURNING id, name, color, category_id
`

type UpdateTagParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color string    `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CategoryID,
	)
	return i, err
}

const updateTagCategory = `-- name: UpdateTagCategory :one
UPDATE tag_categories
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateTagCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateTagCategory(ctx context.Context, arg UpdateTagCategoryParams) (TagCategory, error) {
	row := q.db.QueryRow(ctx, updateTagCategory, arg.ID, arg.Name)
	var i TagCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
