// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const listUsers = `-- name: ListUsers :many
SELECT id, apple_id, created_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.AppleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, apple_id)
VALUES ($1, $2)
ON CONFLICT (apple_id)
DO UPDATE SET apple_id = EXCLUDED.apple_id
RETURNING id, apple_id, created_at
`

type UpsertUserParams struct {
	ID      uuid.UUID `json:"id"`
	AppleID string    `json:"apple_id"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.AppleID)
	var i User
	err := row.Scan(&i.ID, &i.AppleID, &i.CreatedAt)
	return i, err
}
